version: '3'

services:
  app:
    hostname: mireabackend.dev
    container_name: myapp
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.app
      target: prod
    environment:
      - DB_URL=postgres://postgres:mydbpassword@dockerdev.db:5432/postgres?sslmode=disable&

  db:
    hostname: dockerdev.db
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=mydbpassword
    container_name: myapp-db
    ports:
      - "5432:5432"

  mongo:
    hostname: mongo.dev
    image: mongo
    container_name: mongo-db
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword
    ports:
      - "27017:27017"

  web-server:
    build:
      dockerfile: ./Dockerfile.nginx
      context: ../
      target: nginx_prod
    container_name: myapp-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./includes:/etc/nginx/includes
      - ../web:/web
    depends_on:
      - app
      - db
