FROM node:19-alpine3.16 AS frontend
WORKDIR /app
COPY ./web/package.json ./ ./web/package-lock.json ./
RUN npm ci
COPY ./web /app
RUN npm run build

FROM nginx:1.23.3-alpine AS nginx_prod
COPY --from=frontend /app/dist /dist
